# -*- coding: utf-8 -*-
"""PRO-C114: LINEAR REGRESSIONAN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D72jCEmY15OMIlnuhoMCNC8vuTkhBth9
"""

from google.colab import files
files.upload()

import csv
import pandas as pd
import plotly.express as px

df = pd.read_csv("p114.csv")
fig = px.scatter(df, x = "Weight", y="Height")
fig.show()

Height = df["Height"].tolist()
Weight = df["Weight"].tolist()

m = 3
c = 5
y=[]

for x in Height:
  yvalue = m*x + c
  y.append(yvalue)

fig = px.scatter(df, x = "Weight", y="Height")
fig.update_layout(shapes = [
                            dict(
                                type = "line",
                                 y0 = min(y),
                                 y1 = max(y),
                                 x0 = min(Height),
                                 x1 = max(Height)
                            )
])
fig.show()

import numpy as np
weighttarray = np.array(Weight)
heightarray = np.array(Height)
m,c = np.polyfit(heightarray, weighttarray, 1)
y = []

for x in heightarray:
  yvalue = m*x + c
  y.append(yvalue)

fig = px.scatter(df, x = heightarray, y=weighttarray)
fig.update_layout(shapes = [
                            dict(
                                type = "line",
                                 y0 = min(y),
                                 y1 = max(y),
                                 x0 = min(heightarray),
                                 x1 = max(heightarray)
                            )
])
fig.show()